[browser]
serverAddress = '0.0.0.0'

[global]
dataFrameSerialization = "legacy"

[theme]
primaryColor="#E65936"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#1B4053"
font="sans serif"
